angular.module("app")
  .controller('MainController', [MainController])

function MainController($scope) {
  var vm = this;
  vm.properties = [{
    name: "Good Haven",
    address: "1810 High Hill Blvd.",
    dallas: "Yes",
    city: "Dallas",
    state: "Texas",
    zipcode: "75203",
    img: "img/Good Haven - 1.jpg",
    url: "apts/goodhaven",
    pool: "No",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "324",
    latlong: [32.7347291,-96.8008535]
  }, {
    name: "Huntington Meadows",
    address: "7000 Decker Ln.",
    austin: "Yes",
    city: "Austin",
    state: "Texas",
    zipcode: "78724",
    img: "img/Huntington - 1.jpg",
    url: "apts/huntington",
    pool: "Yes",
    pets: "No",
    laundry: "Yes",
    washer: "Yes",
    electric: "No",
    apartments: "200",
    latlong: [30.2967014,-97.6277981]
  }, {
    name: "Park Creek Manor",
    address: "2520 Coombs Creek St.",
    dallas: "Yes",
    city: "Dallas",
    state: "Texas",
    zipcode: "75211",
    img: "img/Park Creek - 1.jpg",
    url: "apts/parkcreekmanor",
    pool: "Yes",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "322",
    latlong: [32.7211541,-96.8807582]
  }, {
    name: "Prairie Ridge Apartments",
    address: "313 Freetown Rd.",
    grand: "Yes",
    city: "Grand Prairie",
    state: "Texas",
    zipcode: "75051",
    img: "img/Prairie Ridge - 1.jpg",
    url: "apts/prairieridge",
    pool: "No",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "100",
    latlong: [32.712475,-97.0118937]
  }, {
    name: "Prince Hall II",
    address: "4820 E. Berry St.",
    fort: "Yes",
    city: "Ft. Worth",
    state: "Texas",
    zipcode: "76105",
    img: "img/image-coming-soon.png",
    url: "apts/princehall",
    pool: "No",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "76",
    latlong: [32.7114663,-97.2526067]
  }, {
    name: "Pythian Manor",
    address: "2719 E. IlliNois Ave. #100",
    dallas: "Yes",
    city: "Dallas",
    state: "Texas",
    zipcode: "75216",
    img: "img/Pythian Manor - 1.jpg",
    url: "apts/pythianmanor",
    pool: "No",
    pets: "No",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "76",
    latlong: [32.7175299,-96.7827407]
  }, {
    name: "Raible Place",
    address: "1216 N. Britain Rd.",
    irving: "Yes",
    city: "Irving",
    state: "Texas",
    zipcode: "75061",
    img: "img/Raible Place - 1.jpg",
    url: "apts/raibleplace",
    pool: "No",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "152",
    latlong: [32.8263606,-96.9444135]
  }, {
    name: "Royal Crest",
    address: "3558 Wilhurt Ave.",
    dallas: "Yes",
    city: "Dallas",
    state: "Texas",
    zipcode: "75216",
    img: "img/Royal Crest - 1.jpg",
    url: "apts/royalcrest",
    pool: "No",
    pets: "No",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "168",
    latlong: [32.7139808,-96.7645486]
  }, {
    name: "Southern Oaks Apartments",
    address: "3424 Southern Oaks Blvd. #13",
    dallas: "Yes",
    city: "Dallas",
    state: "Texas",
    zipcode: "75216",
    img: "img/Southern Oaks - 1.jpg",
    url: "apts/southernoaks",
    pool: "No",
    pets: "Yes",
    laundry: "No",
    washer: "Yes",
    electric: "No",
    apartments: "62",
    latlong: [32.7213674,-96.7732202]
  }, {
    name: "Springdale Apartments",
    address: "1901 Higgins Ln.",
    fort: "Yes",
    city: "Ft. Worth",
    state: "Texas",
    zipcode: "76111",
    img: "img/image-coming-soon.png",
    url: "apts/springdaleapartments",
    pool: "No",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "100",
    latlong: [32.7879642,-97.2876844]
  }, {
    name: "Springdale Estates",
    address: "1050 Springdale Rd.",
    austin: "Yes",
    city: "Austin",
    state: "Texas",
    zipcode: "78721",
    img: "img/Springdale Estates - 1.jpg",
    url: "apts/springdaleestates",
    pool: "Yes",
    pets: "Yes",
    laundry: "No",
    washer: "Yes",
    electric: "No",
    apartments: "43",
    latlong: [30.2708125,-97.6954882]
  }, {
    name: "Terrace View Apartments",
    address: "417 W. Tarrant Road",
    grand: "Yes",
    city: "Grand Prairie",
    state: "Texas",
    zipcode: "75050",
    img: "img/Terrace View - 1.jpg",
    url: "apts/terraceview",
    pool: "No",
    pets: "Yes",
    laundry: "Yes",
    washer: "No",
    electric: "Yes",
    apartments: "192",
    latlong: [32.757114,-97.0118726]
  }, {
    name: "Westmount Place Apartments",
    address: "1441 Westmount Dr.",
    dallas: "Yes",
    city: "Dallas",
    state: "Texas",
    zipcode: "75211",
    img: "img/Westmount Place - 1.jpg",
    url: "apts/westmountplace",
    pool: "Yes",
    pets: "Yes",
    laundry: "No",
    washer: "Yes",
    electric: "No",
    apartments: "70",
    latlong: [32.7609655,-96.8700074]
  }, {
    name: "Winfield Estates",
    address: "3535 South Lake Dr.",
    texarkana: "Yes",
    city: "Texarkana",
    state: "Texas",
    zipcode: "75501",
    img: "img/Winfield Estates - 1.jpg",
    url: "apts/winfieldestates",
    pool: "Yes",
    pets: "Yes",
    laundry: "No",
    washer: "Yes",
    electric: "Yes",
    apartments: "156",
    latlong: [33.3975841,-94.0915925]
  }];
  vm.propertyTypes = {
    austin: "Yes",
    dallas: "Yes",
    grand: "Yes",
    fort: "Yes",
    irving: "Yes",
    texarkana: "Yes",
    pool: "No",
    pets: "No",
    laundry: "No",
    washer: "No",
    electric: "No"
    }
    vm.addCity = function(arg){
      //for var i in city, if arg exists, splice and join
      vm.propertyTypes.city.push(arg);
    }

}
